// 이름 데이터베이스 - 남자 100개, 여자 100개
const PREMIUM_NAMES_MALE = [
    // Wood (목) - 20개
    { name: '건우', hanja: '建宇', meaning: '세상을 세우는 큰 집', element: 'wood', strokes: 20, score: 98 },
    { name: '동현', hanja: '東賢', meaning: '동쪽의 현명함', element: 'wood', strokes: 23, score: 95 },
    { name: '재민', hanja: '在民', meaning: '백성 속에 있음', element: 'wood', strokes: 12, score: 93 },
    { name: '경호', hanja: '京浩', meaning: '서울의 큰 물', element: 'wood', strokes: 19, score: 91 },
    { name: '태경', hanja: '泰京', meaning: '크고 넓은 서울', element: 'wood', strokes: 17, score: 90 },
    { name: '준혁', hanja: '俊赫', meaning: '준수하고 빛남', element: 'wood', strokes: 23, score: 94 },
    { name: '현우', hanja: '賢宇', meaning: '현명한 집', element: 'wood', strokes: 21, score: 92 },
    { name: '동욱', hanja: '東旭', meaning: '동쪽의 아침 해', element: 'wood', strokes: 14, score: 91 },
    { name: '재현', hanja: '在賢', meaning: '현명함 속에 있음', element: 'wood', strokes: 21, score: 93 },
    { name: '경민', hanja: '京民', meaning: '서울의 백성', element: 'wood', strokes: 13, score: 90 },
    { name: '동훈', hanja: '東勳', meaning: '동쪽의 공훈', element: 'wood', strokes: 24, score: 92 },
    { name: '재훈', hanja: '在勳', meaning: '공훈 속에 있음', element: 'wood', strokes: 19, score: 91 },
    { name: '경수', hanja: '京秀', meaning: '서울의 빼어남', element: 'wood', strokes: 15, score: 90 },
    { name: '동진', hanja: '東眞', meaning: '동쪽의 진실', element: 'wood', strokes: 18, score: 92 },
    { name: '재영', hanja: '在永', meaning: '영원 속에 있음', element: 'wood', strokes: 11, score: 89 },
    { name: '경원', hanja: '京源', meaning: '서울의 근원', element: 'wood', strokes: 21, score: 91 },
    { name: '동규', hanja: '東奎', meaning: '동쪽의 별', element: 'wood', strokes: 17, score: 90 },
    { name: '재우', hanja: '在宇', meaning: '집 속에 있음', element: 'wood', strokes: 12, score: 89 },
    { name: '경태', hanja: '京泰', meaning: '서울의 큼', element: 'wood', strokes: 17, score: 91 },
    { name: '동석', hanja: '東錫', meaning: '동쪽의 은', element: 'wood', strokes: 24, score: 92 },

    // Fire (화) - 20개
    { name: '예준', hanja: '睿俊', meaning: '슬기롭고 준수함', element: 'fire', strokes: 24, score: 95 },
    { name: '태양', hanja: '太陽', meaning: '큰 태양', element: 'fire', strokes: 16, score: 97 },
    { name: '지훈', hanja: '智勳', meaning: '지혜로운 공훈', element: 'fire', strokes: 25, score: 94 },
    { name: '승현', hanja: '承賢', meaning: '현명함을 이어받음', element: 'fire', strokes: 23, score: 92 },
    { name: '정우', hanja: '正宇', meaning: '바른 집', element: 'fire', strokes: 11, score: 90 },
    { name: '태민', hanja: '泰民', meaning: '큰 백성', element: 'fire', strokes: 14, score: 91 },
    { name: '준서', hanja: '俊瑞', meaning: '준수하고 상서로움', element: 'fire', strokes: 22, score: 93 },
    { name: '지성', hanja: '智聖', meaning: '지혜롭고 성스러움', element: 'fire', strokes: 25, score: 94 },
    { name: '태현', hanja: '泰賢', meaning: '크고 현명함', element: 'fire', strokes: 23, score: 92 },
    { name: '승민', hanja: '承民', meaning: '백성을 이어받음', element: 'fire', strokes: 13, score: 90 },
    { name: '정민', hanja: '正民', meaning: '바른 백성', element: 'fire', strokes: 10, score: 89 },
    { name: '태준', hanja: '泰俊', meaning: '크고 준수함', element: 'fire', strokes: 18, score: 93 },
    { name: '지민', hanja: '智民', meaning: '지혜로운 백성', element: 'fire', strokes: 17, score: 91 },
    { name: '승준', hanja: '承俊', meaning: '준수함을 이어받음', element: 'fire', strokes: 17, score: 92 },
    { name: '정현', hanja: '正賢', meaning: '바르고 현명함', element: 'fire', strokes: 19, score: 91 },
    { name: '태우', hanja: '泰宇', meaning: '큰 집', element: 'fire', strokes: 15, score: 90 },
    { name: '지원', hanja: '智源', meaning: '지혜의 근원', element: 'fire', strokes: 26, score: 93 },
    { name: '승호', hanja: '承浩', meaning: '넓음을 이어받음', element: 'fire', strokes: 19, score: 91 },
    { name: '정호', hanja: '正浩', meaning: '바르고 넓음', element: 'fire', strokes: 16, score: 90 },
    { name: '태호', hanja: '泰浩', meaning: '크고 넓음', element: 'fire', strokes: 20, score: 92 },

    // Earth (토) - 20개
    { name: '도윤', hanja: '道潤', meaning: '도를 윤택하게 함', element: 'earth', strokes: 25, score: 94 },
    { name: '우진', hanja: '宇眞', meaning: '집의 진실', element: 'earth', strokes: 16, score: 92 },
    { name: '성민', hanja: '聖民', meaning: '성스러운 백성', element: 'earth', strokes: 18, score: 93 },
    { name: '영준', hanja: '永俊', meaning: '영원히 준수함', element: 'earth', strokes: 14, score: 91 },
    { name: '윤호', hanja: '潤浩', meaning: '윤택하고 넓음', element: 'earth', strokes: 26, score: 90 },
    { name: '시우', hanja: '時宇', meaning: '때의 집', element: 'earth', strokes: 16, score: 89 },
    { name: '준영', hanja: '俊永', meaning: '준수하고 영원함', element: 'earth', strokes: 14, score: 92 },
    { name: '성준', hanja: '聖俊', meaning: '성스럽고 준수함', element: 'earth', strokes: 22, score: 93 },
    { name: '영호', hanja: '永浩', meaning: '영원히 넓음', element: 'earth', strokes: 15, score: 91 },
    { name: '윤성', hanja: '潤聖', meaning: '윤택하고 성스러움', element: 'earth', strokes: 29, score: 92 },
    { name: '시현', hanja: '時賢', meaning: '때의 현명함', element: 'earth', strokes: 25, score: 91 },
    { name: '성현', hanja: '聖賢', meaning: '성스럽고 현명함', element: 'earth', strokes: 29, score: 94 },
    { name: '영민', hanja: '永民', meaning: '영원한 백성', element: 'earth', strokes: 10, score: 89 },
    { name: '윤민', hanja: '潤民', meaning: '윤택한 백성', element: 'earth', strokes: 20, score: 90 },
    { name: '시준', hanja: '時俊', meaning: '때의 준수함', element: 'earth', strokes: 19, score: 91 },
    { name: '성우', hanja: '聖宇', meaning: '성스러운 집', element: 'earth', strokes: 19, score: 92 },
    { name: '영우', hanja: '永宇', meaning: '영원한 집', element: 'earth', strokes: 11, score: 90 },
    { name: '윤우', hanja: '潤宇', meaning: '윤택한 집', element: 'earth', strokes: 21, score: 91 },
    { name: '시호', hanja: '時浩', meaning: '때의 넓음', element: 'earth', strokes: 20, score: 90 },
    { name: '성호', hanja: '聖浩', meaning: '성스럽고 넓음', element: 'earth', strokes: 24, score: 93 },

    // Metal (금) - 20개
    { name: '서준', hanja: '瑞俊', meaning: '상서롭고 준수함', element: 'metal', strokes: 23, score: 96 },
    { name: '승우', hanja: '勝宇', meaning: '이기는 집', element: 'metal', strokes: 18, score: 94 },
    { name: '재윤', hanja: '在潤', meaning: '윤택함 속에 있음', element: 'metal', strokes: 21, score: 92 },
    { name: '시현', hanja: '時賢', meaning: '때의 현명함', element: 'metal', strokes: 25, score: 91 },
    { name: '성준', hanja: '聖俊', meaning: '성스럽고 준수함', element: 'metal', strokes: 22, score: 93 },
    { name: '주원', hanja: '周元', meaning: '두루 근본', element: 'metal', strokes: 12, score: 90 },
    { name: '서진', hanja: '瑞眞', meaning: '상서롭고 진실함', element: 'metal', strokes: 23, score: 92 },
    { name: '승민', hanja: '勝民', meaning: '이기는 백성', element: 'metal', strokes: 17, score: 91 },
    { name: '재호', hanja: '在浩', meaning: '넓음 속에 있음', element: 'metal', strokes: 16, score: 90 },
    { name: '서현', hanja: '瑞賢', meaning: '상서롭고 현명함', element: 'metal', strokes: 29, score: 94 },
    { name: '승호', hanja: '勝浩', meaning: '이기고 넓음', element: 'metal', strokes: 21, score: 92 },
    { name: '재준', hanja: '在俊', meaning: '준수함 속에 있음', element: 'metal', strokes: 15, score: 91 },
    { name: '서민', hanja: '瑞民', meaning: '상서로운 백성', element: 'metal', strokes: 18, score: 90 },
    { name: '승준', hanja: '勝俊', meaning: '이기고 준수함', element: 'metal', strokes: 21, score: 93 },
    { name: '재현', hanja: '在賢', meaning: '현명함 속에 있음', element: 'metal', strokes: 21, score: 92 },
    { name: '서호', hanja: '瑞浩', meaning: '상서롭고 넓음', element: 'metal', strokes: 24, score: 91 },
    { name: '승현', hanja: '勝賢', meaning: '이기고 현명함', element: 'metal', strokes: 27, score: 93 },
    { name: '재성', hanja: '在聖', meaning: '성스러움 속에 있음', element: 'metal', strokes: 19, score: 91 },
    { name: '서우', hanja: '瑞宇', meaning: '상서로운 집', element: 'metal', strokes: 19, score: 92 },
    { name: '승성', hanja: '勝聖', meaning: '이기고 성스러움', element: 'metal', strokes: 23, score: 93 },

    // Water (수) - 20개
    { name: '민준', hanja: '敏俊', meaning: '민첩하고 준수함', element: 'water', strokes: 22, score: 97 },
    { name: '지환', hanja: '智煥', meaning: '지혜롭게 빛남', element: 'water', strokes: 25, score: 95 },
    { name: '현준', hanja: '賢俊', meaning: '현명하고 준수함', element: 'water', strokes: 25, score: 94 },
    { name: '민성', hanja: '敏聖', meaning: '민첩하고 성스러움', element: 'water', strokes: 24, score: 92 },
    { name: '지원', hanja: '智源', meaning: '지혜의 근원', element: 'water', strokes: 26, score: 93 },
    { name: '하준', hanja: '夏俊', meaning: '여름의 준수함', element: 'water', strokes: 19, score: 91 },
    { name: '민재', hanja: '敏在', meaning: '민첩하게 있음', element: 'water', strokes: 17, score: 90 },
    { name: '지후', hanja: '智厚', meaning: '지혜롭고 두터움', element: 'water', strokes: 21, score: 92 },
    { name: '현우', hanja: '賢宇', meaning: '현명한 집', element: 'water', strokes: 21, score: 93 },
    { name: '민호', hanja: '敏浩', meaning: '민첩하고 넓음', element: 'water', strokes: 21, score: 91 },
    { name: '지안', hanja: '智安', meaning: '지혜롭고 편안함', element: 'water', strokes: 18, score: 90 },
    { name: '하윤', hanja: '夏潤', meaning: '여름의 윤택함', element: 'water', strokes: 26, score: 92 },
    { name: '민우', hanja: '敏宇', meaning: '민첩한 집', element: 'water', strokes: 17, score: 91 },
    { name: '지훈', hanja: '智勳', meaning: '지혜로운 공훈', element: 'water', strokes: 25, score: 94 },
    { name: '현민', hanja: '賢民', meaning: '현명한 백성', element: 'water', strokes: 20, score: 92 },
    { name: '민현', hanja: '敏賢', meaning: '민첩하고 현명함', element: 'water', strokes: 26, score: 93 },
    { name: '지성', hanja: '智聖', meaning: '지혜롭고 성스러움', element: 'water', strokes: 25, score: 94 },
    { name: '하민', hanja: '夏民', meaning: '여름의 백성', element: 'water', strokes: 15, score: 90 },
    { name: '민석', hanja: '敏錫', meaning: '민첩하고 은같음', element: 'water', strokes: 27, score: 92 },
    { name: '지우', hanja: '智宇', meaning: '지혜로운 집', element: 'water', strokes: 18, score: 91 }
];

const PREMIUM_NAMES_FEMALE = [
    // Wood (목) - 20개
    { name: '지우', hanja: '智優', meaning: '지혜롭고 우수함', element: 'wood', strokes: 29, score: 95 },
    { name: '수빈', hanja: '秀彬', meaning: '빼어나고 빛남', element: 'wood', strokes: 18, score: 93 },
    { name: '예린', hanja: '藝璘', meaning: '예술적이고 아름다운 옥', element: 'wood', strokes: 35, score: 92 },
    { name: '가은', hanja: '佳恩', meaning: '아름다운 은혜', element: 'wood', strokes: 18, score: 91 },
    { name: '채원', hanja: '采園', meaning: '정원을 가꿈', element: 'wood', strokes: 20, score: 90 },
    { name: '수아', hanja: '秀雅', meaning: '빼어나고 우아함', element: 'wood', strokes: 19, score: 92 },
    { name: '예은', hanja: '藝恩', meaning: '예술의 은혜', element: 'wood', strokes: 31, score: 91 },
    { name: '가연', hanja: '佳妍', meaning: '아름답고 곱다', element: 'wood', strokes: 15, score: 90 },
    { name: '수연', hanja: '秀妍', meaning: '빼어나고 아름다움', element: 'wood', strokes: 14, score: 92 },
    { name: '예원', hanja: '藝園', meaning: '예술의 정원', element: 'wood', strokes: 32, score: 91 },
    { name: '가영', hanja: '佳英', meaning: '아름답고 빛남', element: 'wood', strokes: 16, score: 90 },
    { name: '수영', hanja: '秀英', meaning: '빼어나고 빛남', element: 'wood', strokes: 15, score: 91 },
    { name: '예지', hanja: '藝智', meaning: '예술과 지혜', element: 'wood', strokes: 33, score: 92 },
    { name: '가인', hanja: '佳仁', meaning: '아름답고 어짊', element: 'wood', strokes: 12, score: 89 },
    { name: '수진', hanja: '秀眞', meaning: '빼어나고 진실함', element: 'wood', strokes: 17, score: 91 },
    { name: '예진', hanja: '藝眞', meaning: '예술과 진실', element: 'wood', strokes: 31, score: 92 },
    { name: '가현', hanja: '佳賢', meaning: '아름답고 현명함', element: 'wood', strokes: 23, score: 91 },
    { name: '수현', hanja: '秀賢', meaning: '빼어나고 현명함', element: 'wood', strokes: 22, score: 93 },
    { name: '예빈', hanja: '藝彬', meaning: '예술적이고 빛남', element: 'wood', strokes: 32, score: 91 },
    { name: '가희', hanja: '佳姬', meaning: '아름답고 기쁨', element: 'wood', strokes: 18, score: 90 },

    // Fire (화) - 20개
    { name: '하은', hanja: '夏恩', meaning: '여름의 은혜', element: 'fire', strokes: 20, score: 96 },
    { name: '지민', hanja: '智敏', meaning: '지혜롭고 민첩함', element: 'fire', strokes: 23, score: 94 },
    { name: '다은', hanja: '多恩', meaning: '많은 은혜', element: 'fire', strokes: 16, score: 92 },
    { name: '예나', hanja: '睿娜', meaning: '슬기롭고 아름다움', element: 'fire', strokes: 24, score: 93 },
    { name: '지현', hanja: '智賢', meaning: '지혜롭고 현명함', element: 'fire', strokes: 27, score: 95 },
    { name: '태희', hanja: '泰姬', meaning: '크고 아름다움', element: 'fire', strokes: 19, score: 91 },
    { name: '다인', hanja: '多仁', meaning: '많은 어짊', element: 'fire', strokes: 10, score: 90 },
    { name: '하연', hanja: '夏妍', meaning: '여름의 아름다움', element: 'fire', strokes: 17, score: 92 },
    { name: '지연', hanja: '智妍', meaning: '지혜롭고 아름다움', element: 'fire', strokes: 19, score: 93 },
    { name: '다연', hanja: '多妍', meaning: '많이 아름다움', element: 'fire', strokes: 13, score: 91 },
    { name: '예림', hanja: '睿林', meaning: '슬기로운 숲', element: 'fire', strokes: 22, score: 92 },
    { name: '지영', hanja: '智英', meaning: '지혜롭고 빛남', element: 'fire', strokes: 20, score: 94 },
    { name: '하영', hanja: '夏英', meaning: '여름의 빛남', element: 'fire', strokes: 18, score: 91 },
    { name: '다영', hanja: '多英', meaning: '많이 빛남', element: 'fire', strokes: 15, score: 90 },
    { name: '예서', hanja: '睿瑞', meaning: '슬기롭고 상서로움', element: 'fire', strokes: 27, score: 93 },
    { name: '지서', hanja: '智瑞', meaning: '지혜롭고 상서로움', element: 'fire', strokes: 25, score: 94 },
    { name: '하서', hanja: '夏瑞', meaning: '여름의 상서로움', element: 'fire', strokes: 23, score: 92 },
    { name: '다현', hanja: '多賢', meaning: '많이 현명함', element: 'fire', strokes: 21, score: 91 },
    { name: '예주', hanja: '睿珠', meaning: '슬기로운 구슬', element: 'fire', strokes: 25, score: 92 },
    { name: '지아', hanja: '智雅', meaning: '지혜롭고 우아함', element: 'fire', strokes: 24, score: 95 },

    // Earth (토) - 20개
    { name: '유진', hanja: '有眞', meaning: '진실을 가짐', element: 'earth', strokes: 16, score: 93 },
    { name: '윤서', hanja: '潤瑞', meaning: '윤택하고 상서로움', element: 'earth', strokes: 29, score: 92 },
    { name: '서윤', hanja: '瑞潤', meaning: '상서롭고 윤택함', element: 'earth', strokes: 29, score: 94 },
    { name: '은서', hanja: '恩瑞', meaning: '은혜롭고 상서로움', element: 'earth', strokes: 23, score: 91 },
    { name: '유나', hanja: '有娜', meaning: '아름다움을 가짐', element: 'earth', strokes: 15, score: 90 },
    { name: '윤아', hanja: '潤雅', meaning: '윤택하고 우아함', element: 'earth', strokes: 28, score: 92 },
    { name: '서아', hanja: '瑞雅', meaning: '상서롭고 우아함', element: 'earth', strokes: 26, score: 91 },
    { name: '유빈', hanja: '有彬', meaning: '빛남을 가짐', element: 'earth', strokes: 17, score: 90 },
    { name: '윤지', hanja: '潤智', meaning: '윤택하고 지혜로움', element: 'earth', strokes: 28, score: 93 },
    { name: '서지', hanja: '瑞智', meaning: '상서롭고 지혜로움', element: 'earth', strokes: 26, score: 92 },
    { name: '은지', hanja: '恩智', meaning: '은혜롭고 지혜로움', element: 'earth', strokes: 22, score: 91 },
    { name: '유경', hanja: '有京', meaning: '서울을 가짐', element: 'earth', strokes: 14, score: 90 },
    { name: '윤경', hanja: '潤京', meaning: '윤택한 서울', element: 'earth', strokes: 24, score: 91 },
    { name: '서경', hanja: '瑞京', meaning: '상서로운 서울', element: 'earth', strokes: 22, score: 92 },
    { name: '은경', hanja: '恩京', meaning: '은혜로운 서울', element: 'earth', strokes: 18, score: 90 },
    { name: '유민', hanja: '有民', meaning: '백성을 가짐', element: 'earth', strokes: 11, score: 89 },
    { name: '윤민', hanja: '潤民', meaning: '윤택한 백성', element: 'earth', strokes: 20, score: 90 },
    { name: '서민', hanja: '瑞民', meaning: '상서로운 백성', element: 'earth', strokes: 18, score: 91 },
    { name: '은민', hanja: '恩民', meaning: '은혜로운 백성', element: 'earth', strokes: 15, score: 90 },
    { name: '유주', hanja: '有珠', meaning: '구슬을 가짐', element: 'earth', strokes: 16, score: 91 },

    // Metal (금) - 20개
    { name: '서연', hanja: '瑞妍', meaning: '상서롭고 아름다움', element: 'metal', strokes: 23, score: 98 },
    { name: '채은', hanja: '采恩', meaning: '은혜를 가꿈', element: 'metal', strokes: 18, score: 94 },
    { name: '서현', hanja: '瑞賢', meaning: '상서롭고 현명함', element: 'metal', strokes: 29, score: 95 },
    { name: '소율', hanja: '昭律', meaning: '밝은 법칙', element: 'metal', strokes: 17, score: 92 },
    { name: '서영', hanja: '瑞英', meaning: '상서롭고 빛남', element: 'metal', strokes: 22, score: 93 },
    { name: '채린', hanja: '采璘', meaning: '아름다운 옥을 가꿈', element: 'metal', strokes: 25, score: 91 },
    { name: '서희', hanja: '瑞姬', meaning: '상서롭고 아름다움', element: 'metal', strokes: 23, score: 92 },
    { name: '소연', hanja: '昭妍', meaning: '밝고 아름다움', element: 'metal', strokes: 16, score: 91 },
    { name: '채영', hanja: '采英', meaning: '빛남을 가꿈', element: 'metal', strokes: 15, score: 90 },
    { name: '서진', hanja: '瑞眞', meaning: '상서롭고 진실함', element: 'metal', strokes: 23, score: 93 },
    { name: '소영', hanja: '昭英', meaning: '밝고 빛남', element: 'metal', strokes: 17, score: 92 },
    { name: '채현', hanja: '采賢', meaning: '현명함을 가꿈', element: 'metal', strokes: 24, score: 93 },
    { name: '서빈', hanja: '瑞彬', meaning: '상서롭고 빛남', element: 'metal', strokes: 24, score: 91 },
    { name: '소현', hanja: '昭賢', meaning: '밝고 현명함', element: 'metal', strokes: 23, score: 93 },
    { name: '채윤', hanja: '采潤', meaning: '윤택함을 가꿈', element: 'metal', strokes: 23, score: 92 },
    { name: '서주', hanja: '瑞珠', meaning: '상서로운 구슬', element: 'metal', strokes: 24, score: 91 },
    { name: '소윤', hanja: '昭潤', meaning: '밝고 윤택함', element: 'metal', strokes: 24, score: 92 },
    { name: '채아', hanja: '采雅', meaning: '우아함을 가꿈', element: 'metal', strokes: 20, score: 91 },
    { name: '서민', hanja: '瑞民', meaning: '상서로운 백성', element: 'metal', strokes: 18, score: 90 },
    { name: '소아', hanja: '昭雅', meaning: '밝고 우아함', element: 'metal', strokes: 21, score: 91 },

    // Water (수) - 20개
    { name: '지아', hanja: '智雅', meaning: '지혜롭고 우아함', element: 'water', strokes: 24, score: 99 },
    { name: '민서', hanja: '敏瑞', meaning: '민첩하고 상서로움', element: 'water', strokes: 25, score: 97 },
    { name: '하윤', hanja: '夏潤', meaning: '여름의 윤택함', element: 'water', strokes: 26, score: 95 },
    { name: '민지', hanja: '敏智', meaning: '민첩하고 지혜로움', element: 'water', strokes: 23, score: 94 },
    { name: '지윤', hanja: '智潤', meaning: '지혜롭고 윤택함', element: 'water', strokes: 28, score: 96 },
    { name: '하린', hanja: '夏璘', meaning: '여름의 아름다운 옥', element: 'water', strokes: 27, score: 93 },
    { name: '민주', hanja: '敏珠', meaning: '민첩한 구슬', element: 'water', strokes: 21, score: 92 },
    { name: '지수', hanja: '智秀', meaning: '지혜롭고 빼어남', element: 'water', strokes: 19, score: 94 },
    { name: '하진', hanja: '夏眞', meaning: '여름의 진실', element: 'water', strokes: 20, score: 92 },
    { name: '민아', hanja: '敏雅', meaning: '민첩하고 우아함', element: 'water', strokes: 23, score: 93 },
    { name: '지혜', hanja: '智慧', meaning: '지혜', element: 'water', strokes: 27, score: 95 },
    { name: '하영', hanja: '夏英', meaning: '여름의 빛남', element: 'water', strokes: 18, score: 91 },
    { name: '민영', hanja: '敏英', meaning: '민첩하고 빛남', element: 'water', strokes: 20, score: 92 },
    { name: '지원', hanja: '智源', meaning: '지혜의 근원', element: 'water', strokes: 26, score: 94 },
    { name: '하나', hanja: '夏娜', meaning: '여름의 아름다움', element: 'water', strokes: 19, score: 91 },
    { name: '민경', hanja: '敏京', meaning: '민첩한 서울', element: 'water', strokes: 19, score: 90 },
    { name: '지은', hanja: '智恩', meaning: '지혜로운 은혜', element: 'water', strokes: 22, score: 93 },
    { name: '하빈', hanja: '夏彬', meaning: '여름의 빛남', element: 'water', strokes: 21, score: 92 },
    { name: '민희', hanja: '敏姬', meaning: '민첩하고 아름다움', element: 'water', strokes: 20, score: 91 },
    { name: '지인', hanja: '智仁', meaning: '지혜롭고 어짊', element: 'water', strokes: 16, score: 92 }
];
